pages:
  stage: deploy
  tags:
    - itup-alm-x86
  script:
    - mkdir -p public
    - cp "index.html" public/index.html
    - cp ai-asset-mess.jpeg public/ || true
    - cp ai-assets-sot.jpeg public/ || true
    - cp ai-asset-methodology-favicon.svg public/ || true
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
